# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Columbus < Formula
  desc "Metadata Discovery and Lineage Service"
  homepage "https://github.com/odpf/columbus"
  version "0.1.8"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/odpf/columbus/releases/download/v0.1.8/columbus_0.1.8_macos_x86_64.tar.gz"
      sha256 "4ab933275a33a1d05f2d20f6f48cc10635c8c85d04fea2ede4333ba05f64cdf9"

      def install
        bin.install "columbus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/odpf/columbus/releases/download/v0.1.8/columbus_0.1.8_macos_arm64.tar.gz"
      sha256 "9d6b89a9b47019c313eed34c5e50f525dbce5777f45c3ca43a14df35072b05e1"

      def install
        bin.install "columbus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/odpf/columbus/releases/download/v0.1.8/columbus_0.1.8_linux_x86_64.tar.gz"
      sha256 "9162fd2e960882b4cc4769b0d92c4e0e76d13f5a645905680cdc4761ac052f4a"

      def install
        bin.install "columbus"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/odpf/columbus/releases/download/v0.1.8/columbus_0.1.8_linux_armv6.tar.gz"
      sha256 "37ba3aafe60cdaa85a6fc216ac5b26f41da632437035177c7bd46224a7a35ad3"

      def install
        bin.install "columbus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/odpf/columbus/releases/download/v0.1.8/columbus_0.1.8_linux_arm64.tar.gz"
      sha256 "c7856ba17c8418bfc2c53cda9e35adfec2fa9a4da9d782611352c89364a37373"

      def install
        bin.install "columbus"
      end
    end
  end

  depends_on "git"
end
