# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Compass < Formula
  desc "Metadata Discovery and Lineage Service"
  homepage "https://github.com/odpf/compass"
  version "0.3.0"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/odpf/compass/releases/download/v0.3.0/compass_0.3.0_macos_arm64.tar.gz"
      sha256 "536dbcf94de31bc1700efd2a00f7fec1d94492b2010c345ae084309b3e1b6743"

      def install
        bin.install "compass"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/odpf/compass/releases/download/v0.3.0/compass_0.3.0_macos_x86_64.tar.gz"
      sha256 "7c1c7d51008fea8a7e589d767019bda7b844fb64a86b35363183401c5e50e168"

      def install
        bin.install "compass"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/odpf/compass/releases/download/v0.3.0/compass_0.3.0_linux_x86_64.tar.gz"
      sha256 "435180ea3718aa1e83c27eb54daa4470de6ac34f5f0e133961c38df1fbce4d6a"

      def install
        bin.install "compass"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/odpf/compass/releases/download/v0.3.0/compass_0.3.0_linux_arm64.tar.gz"
      sha256 "921fbd5ab83787d2cf2c5bceb45dab90498244be64122d8be731d6b88def5626"

      def install
        bin.install "compass"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/odpf/compass/releases/download/v0.3.0/compass_0.3.0_linux_armv6.tar.gz"
      sha256 "c6484e965ccf471f814d620d276ad0f6a8b5b004a245b5b758e94c89ba926d6d"

      def install
        bin.install "compass"
      end
    end
  end
end
