# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dex < Formula
  desc "Infrastructure orchestration tool."
  homepage "https://github.com/odpf/dex"
  version "0.1.0"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/odpf/dex/releases/download/v0.1.0/dex_0.1.0_macos_x86_64.tar.gz"
      sha256 "aa401258bea570c8d699898ad9d81647ab27b204a80bcae1ebcfd3a059c16000"

      def install
        bin.install "dex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/odpf/dex/releases/download/v0.1.0/dex_0.1.0_macos_arm64.tar.gz"
      sha256 "429384da58fd68ca322bde025339a7263bb0f5b55862637d4ffbad62437452f5"

      def install
        bin.install "dex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/odpf/dex/releases/download/v0.1.0/dex_0.1.0_linux_arm64.tar.gz"
      sha256 "e4cd712fb717ff0f4b150f0bd237013af7bf4a69e59e3a17cbe62bddd3063131"

      def install
        bin.install "dex"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/odpf/dex/releases/download/v0.1.0/dex_0.1.0_linux_x86_64.tar.gz"
      sha256 "ddd25f57abde32960ee8470ebb1699961b12d3621b0292b346994f3dc04d80a5"

      def install
        bin.install "dex"
      end
    end
  end
end
