# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dex < Formula
  desc "Infrastructure orchestration tool."
  homepage "https://github.com/odpf/dex"
  version "0.2.1"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/odpf/dex/releases/download/v0.2.1/dex_0.2.1_macos_arm64.tar.gz"
      sha256 "484ba0e57eee6a2c327ec57ea0a7091efc1429c58029c26ecc38fd79d74cfdc4"

      def install
        bin.install "dex"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/odpf/dex/releases/download/v0.2.1/dex_0.2.1_macos_x86_64.tar.gz"
      sha256 "974dc500b2c2a717386fef1447c6d50c9dbe49a49eef7c49ec23afb9a3bc31aa"

      def install
        bin.install "dex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/odpf/dex/releases/download/v0.2.1/dex_0.2.1_linux_x86_64.tar.gz"
      sha256 "783d611ee420aab60a766bf1b62b82e4e52f95c84a267bc8f67130bc966f4ae9"

      def install
        bin.install "dex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/odpf/dex/releases/download/v0.2.1/dex_0.2.1_linux_arm64.tar.gz"
      sha256 "9792400f3873b45a8dfe979a5b8d533f723134a219496382f8f103808aa8b3f3"

      def install
        bin.install "dex"
      end
    end
  end
end
