# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Entropy < Formula
  desc "Infrastructure orchestration tool."
  homepage "https://github.com/raystack/entropy"
  version "0.2.0"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/raystack/entropy/releases/download/v0.2.0/entropy_0.2.0_macos_arm64.tar.gz"
      sha256 "4fd42bd022a91c3651a9748a9463d80d5df192173f57022303dc5bdd2aca9463"

      def install
        bin.install "entropy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/raystack/entropy/releases/download/v0.2.0/entropy_0.2.0_macos_x86_64.tar.gz"
      sha256 "530dd8c04814c23bb97e98c0d3bd61ee2652580bd672461de2905e3273fde2ad"

      def install
        bin.install "entropy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/raystack/entropy/releases/download/v0.2.0/entropy_0.2.0_linux_x86_64.tar.gz"
      sha256 "e9c1164911c9fb10ad665085b718f1f957cb1a394e1bbae2a503a166d79845a8"

      def install
        bin.install "entropy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/raystack/entropy/releases/download/v0.2.0/entropy_0.2.0_linux_arm64.tar.gz"
      sha256 "ea4302f4d5c368a625fee28d8d9bd53336ca95a491964b4f6e1a7937974d9c44"

      def install
        bin.install "entropy"
      end
    end
  end
end
