# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Entropy < Formula
  desc "Infrastructure orchestration tool."
  homepage "https://github.com/odpf/entropy"
  version "0.1.5"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/odpf/entropy/releases/download/v0.1.5/entropy_0.1.5_macos_arm64.tar.gz"
      sha256 "dca4481727e99e8b1c279e9d1e61687cafe3359cf678163558dc46e32d7d7045"

      def install
        bin.install "entropy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/odpf/entropy/releases/download/v0.1.5/entropy_0.1.5_macos_x86_64.tar.gz"
      sha256 "0aa62610552069f5ccdca8be215f203997587ffb7f4f46427cc121084b672e22"

      def install
        bin.install "entropy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/odpf/entropy/releases/download/v0.1.5/entropy_0.1.5_linux_arm64.tar.gz"
      sha256 "83344ec3217ce080810d584663cc051ccc16147366e99b40ff6d9dda364b7a27"

      def install
        bin.install "entropy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/odpf/entropy/releases/download/v0.1.5/entropy_0.1.5_linux_x86_64.tar.gz"
      sha256 "47531c0f22eec5466b88af6d9f738ae0a3d94cbd032e9e34d9e52e16e5613a09"

      def install
        bin.install "entropy"
      end
    end
  end
end
