# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Frontier < Formula
  desc "Identity and authorization system"
  homepage "https://github.com/raystack/frontier"
  version "0.7.16"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/raystack/frontier/releases/download/v0.7.16/frontier_Darwin_x86_64.tar.gz"
      sha256 "e189e87e5b33ce8780311f3ff43f641da919f63fd7a800b99f9c96dbd8ce1ed9"

      def install
        bin.install "frontier"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/raystack/frontier/releases/download/v0.7.16/frontier_Darwin_arm64.tar.gz"
      sha256 "6e05772016dd430f71d76bc4153b99841021fe494ecd47aa19063eb5edd88ffd"

      def install
        bin.install "frontier"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/raystack/frontier/releases/download/v0.7.16/frontier_Linux_arm64.tar.gz"
      sha256 "61e06b5eb2d89fbcaec9ff6b824e7e710719f1d1a3e8ab4fa8ec50f562cee35d"

      def install
        bin.install "frontier"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/raystack/frontier/releases/download/v0.7.16/frontier_Linux_x86_64.tar.gz"
      sha256 "b627dbd9005581e63f5829ba3e604d20f0493aef14f456b057a6e241c6e378a9"

      def install
        bin.install "frontier"
      end
    end
  end
end
