# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Frontier < Formula
  desc "Identity and authorization system"
  homepage "https://github.com/raystack/frontier"
  version "0.28.0"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    on_intel do
      url "https://github.com/raystack/frontier/releases/download/v0.28.0/frontier_Darwin_x86_64.tar.gz"
      sha256 "eede9cb666cb3fee41ae0e405d22aa684b7b97d498938f793015087cad4abe52"

      def install
        bin.install "frontier"
      end
    end
    on_arm do
      url "https://github.com/raystack/frontier/releases/download/v0.28.0/frontier_Darwin_arm64.tar.gz"
      sha256 "04be1b409e46cf809d06966baac6f49720627f3d37f98bc929dab5ed6995f7d0"

      def install
        bin.install "frontier"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/raystack/frontier/releases/download/v0.28.0/frontier_Linux_x86_64.tar.gz"
        sha256 "5ab86ca8a73963d89dba5f679bf3cd6df18970991fba0744531f75707ce30db3"

        def install
          bin.install "frontier"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/raystack/frontier/releases/download/v0.28.0/frontier_Linux_arm64.tar.gz"
        sha256 "56441b68b8285009c3af87509299526a23111db28b38f191128e1bd541b848e7"

        def install
          bin.install "frontier"
        end
      end
    end
  end
end
