# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Guardian < Formula
  desc "Universal data access tool"
  homepage "https://github.com/raystack/guardian"
  version "0.7.0"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/raystack/guardian/releases/download/v0.7.0/guardian_0.7.0_macos_arm64.tar.gz"
      sha256 "b9e2a4a42b36dfe3b86bbe41342433cd4fcba16263c5cd595bb71d57803384fd"

      def install
        bin.install "guardian"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/raystack/guardian/releases/download/v0.7.0/guardian_0.7.0_macos_x86_64.tar.gz"
      sha256 "ff85571c2788d955ec529ab872662f1e7f6f829db148081bb00e085e62320101"

      def install
        bin.install "guardian"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/raystack/guardian/releases/download/v0.7.0/guardian_0.7.0_linux_arm64.tar.gz"
      sha256 "b27be417df9c9713bbd0ff601c6a69e8ada166e5a106335f92ad76dbe1a5cc95"

      def install
        bin.install "guardian"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/raystack/guardian/releases/download/v0.7.0/guardian_0.7.0_linux_armv6.tar.gz"
      sha256 "65cbe37e7041b73ac486a073aa3ee027f2fbdecbbb1dd83aef39d32ae7b25dbd"

      def install
        bin.install "guardian"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/raystack/guardian/releases/download/v0.7.0/guardian_0.7.0_linux_x86_64.tar.gz"
      sha256 "6fd0a2aecc851b52b9e5264804538f401734ec9f997a91b52d485ba1612c3d6f"

      def install
        bin.install "guardian"
      end
    end
  end
end
