# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Guardian < Formula
  desc "Universal data access tool"
  homepage "https://github.com/odpf/guardian"
  version "0.6.0-alpha.3"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/odpf/guardian/releases/download/v0.6.0-alpha.3/guardian_0.6.0-alpha.3_macos_arm64.tar.gz"
      sha256 "b147defce2977f59dfe27c8bfec46412109efd601e593a4f92770043f89e36a0"

      def install
        bin.install "guardian"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/odpf/guardian/releases/download/v0.6.0-alpha.3/guardian_0.6.0-alpha.3_macos_x86_64.tar.gz"
      sha256 "263415f0bef0ec62bebc51ef4ef60fc2c811050fe994b2af1f3cc397a07bca9d"

      def install
        bin.install "guardian"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/odpf/guardian/releases/download/v0.6.0-alpha.3/guardian_0.6.0-alpha.3_linux_armv6.tar.gz"
      sha256 "92c037b15218d2e4109c291f95ca0ae6b984f05d35987d0092823f702bd1665a"

      def install
        bin.install "guardian"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/odpf/guardian/releases/download/v0.6.0-alpha.3/guardian_0.6.0-alpha.3_linux_x86_64.tar.gz"
      sha256 "077d9639c1ecd8f1185b8957e76a328d50f85c05e14c0e03d7fc8a6fdfc2ea43"

      def install
        bin.install "guardian"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/odpf/guardian/releases/download/v0.6.0-alpha.3/guardian_0.6.0-alpha.3_linux_arm64.tar.gz"
      sha256 "18ca2baf26cc6ba3c7dc568acd33fc67c3ae3d1c922e9acc21a6675c4c62c9b7"

      def install
        bin.install "guardian"
      end
    end
  end
end
