# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meteor < Formula
  desc "Metadata collection tool."
  homepage "https://github.com/odpf/meteor"
  version "0.1.17"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/odpf/meteor/releases/download/v0.1.17/meteor_0.1.17_macos_arm64.tar.gz"
      sha256 "b3e5a6fd9bbe7998abbbde44a92b0e0f8085df2a7e86fe575b0578dc0d209561"

      def install
        bin.install "meteor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/odpf/meteor/releases/download/v0.1.17/meteor_0.1.17_macos_x86_64.tar.gz"
      sha256 "1f33a8a662b55c4990d150776a874057e6faaf74f1e76ce41b53d2f55dd12309"

      def install
        bin.install "meteor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/odpf/meteor/releases/download/v0.1.17/meteor_0.1.17_linux_arm64.tar.gz"
      sha256 "d422ef2e39a2da747a6973086a2e3f7354de93e5930d792e9b9bec58032d9e85"

      def install
        bin.install "meteor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/odpf/meteor/releases/download/v0.1.17/meteor_0.1.17_linux_x86_64.tar.gz"
      sha256 "08f3775d77bb60f9c39c17a340e9079839783132112c240a9732c809ee726ae4"

      def install
        bin.install "meteor"
      end
    end
  end

  depends_on "git"
end
