# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meteor < Formula
  desc "Metadata collection tool."
  homepage "https://github.com/odpf/meteor"
  version "0.3.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/odpf/meteor/releases/download/v0.3.0/meteor_0.3.0_macos_x86_64.tar.gz"
      sha256 "acc00c98a11c81f60b273226ba431eac528b3afa162dde01fa8b383716e90d7f"

      def install
        bin.install "meteor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/odpf/meteor/releases/download/v0.3.0/meteor_0.3.0_macos_arm64.tar.gz"
      sha256 "23f8b9b5a5536e5b4682f9dd35d084c0665bd1f5dbf3ede68e24454c83917680"

      def install
        bin.install "meteor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/odpf/meteor/releases/download/v0.3.0/meteor_0.3.0_linux_arm64.tar.gz"
      sha256 "56a50a150966feb7956ad5eab41dc8881f95f1cd0105a2144bb7b42cccde1b26"

      def install
        bin.install "meteor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/odpf/meteor/releases/download/v0.3.0/meteor_0.3.0_linux_x86_64.tar.gz"
      sha256 "332e90bc3c2ea4a7504082da1bc88ac5676f103ee46d635d34256a9a42e1107a"

      def install
        bin.install "meteor"
      end
    end
  end

  depends_on "git"
end
