# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meteor < Formula
  desc "Metadata collection tool."
  homepage "https://github.com/odpf/meteor"
  version "0.5.1"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/odpf/meteor/releases/download/v0.5.1/meteor_0.5.1_macos_arm64.tar.gz"
      sha256 "febbec3d2032538c7691d0c4718e5fc113af366478a00fb6325fb0915d5e970a"

      def install
        bin.install "meteor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/odpf/meteor/releases/download/v0.5.1/meteor_0.5.1_macos_x86_64.tar.gz"
      sha256 "14a04ea563c7ed82118765856aa9c629348872c36dede1a10a993567359355a2"

      def install
        bin.install "meteor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/odpf/meteor/releases/download/v0.5.1/meteor_0.5.1_linux_x86_64.tar.gz"
      sha256 "9f712d4d8e2895901b0b6bec0fc61b41b6c5f77a12f8cf219b02f57db8c0fa89"

      def install
        bin.install "meteor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/odpf/meteor/releases/download/v0.5.1/meteor_0.5.1_linux_arm64.tar.gz"
      sha256 "4c3b9d28e8d12a303e40ebf58711e7729c45a5961764332f433e5f52462dd46c"

      def install
        bin.install "meteor"
      end
    end
  end

  depends_on "git"
end
