# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Optimus < Formula
  desc "Optimus helps your organization to build & manage data pipelines with ease."
  homepage "https://odpf.github.io/optimus"
  version "0.0.5-rc.3"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/odpf/optimus/releases/download/v0.0.5-rc.3/optimus_0.0.5-rc.3_macos_x86_64.tar.gz"
      sha256 "609de9c2a6cbc6a1d3359b8be03fa23e6f1c60154b06268973625ee1e0e209a6"

      def install
        bin.install "optimus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/odpf/optimus/releases/download/v0.0.5-rc.3/optimus_0.0.5-rc.3_macos_arm64.tar.gz"
      sha256 "1294d032302c6396203b73c58c13ffb1f2c6f89297d6caed15a231fb07f1c835"

      def install
        bin.install "optimus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/odpf/optimus/releases/download/v0.0.5-rc.3/optimus_0.0.5-rc.3_linux_x86_64.tar.gz"
      sha256 "280b746de87899b27ccdca1a1a758c413286b21bfd7a0c39f3006631a21e69ae"

      def install
        bin.install "optimus"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/odpf/optimus/releases/download/v0.0.5-rc.3/optimus_0.0.5-rc.3_linux_armv6.tar.gz"
      sha256 "72ffad1eca4dadd361d068911f772de5cebcd4f753a6f9c30e5c3eb80b94a976"

      def install
        bin.install "optimus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/odpf/optimus/releases/download/v0.0.5-rc.3/optimus_0.0.5-rc.3_linux_arm64.tar.gz"
      sha256 "e505390cd083840a24dfe4142cd8f04ddf5f73c6b2f76ca3ac0f665a475f451d"

      def install
        bin.install "optimus"
      end
    end
  end

  depends_on "git"
end
