# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OptimusPluginsOdpf < Formula
  desc "Optimus Plugins for warehouse"
  homepage ""
  version "0.1.6"
  license "Apache 2.0"

  depends_on "odpf/taps/optimus"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/odpf/transformers/releases/download/v0.1.6/transformers_0.1.6_macos_x86_64.tar.gz"
      sha256 "0f6f55d6247b4ad57bb98c8727bd610b886aa2b023d199a6b6a2269905aa48f7"

      def install
        bin.install Dir["optimus-*"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/odpf/transformers/releases/download/v0.1.6/transformers_0.1.6_macos_arm64.tar.gz"
      sha256 "4be40dd23d10b6721c81aa2f71f6f2b66f2a4256776e1e1e02772110c4be9d18"

      def install
        bin.install Dir["optimus-*"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/odpf/transformers/releases/download/v0.1.6/transformers_0.1.6_linux_arm64.tar.gz"
      sha256 "9cf8d6b96a2903f0305a79a8c74f9f8b60c7c11db1e34d1b86a84094d12412d9"

      def install
        bin.install Dir["optimus-*"]
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/odpf/transformers/releases/download/v0.1.6/transformers_0.1.6_linux_x86_64.tar.gz"
      sha256 "ceda92761b11fb9d95d7a520167cc1cb34848cccee3b252ca02dcf3b6b7d9d4e"

      def install
        bin.install Dir["optimus-*"]
      end
    end
  end
end
