# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Optimus < Formula
  desc "Optimus helps your organization to build & manage data pipelines with ease."
  homepage "https://odpf.github.io/optimus"
  version "0.3.6"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/odpf/optimus/releases/download/v0.3.6/optimus_0.3.6_macos_x86_64.tar.gz"
      sha256 "5eebf1ffc52dc0c831c3504f1c4227819d793cf52153e6b7ea0ce2f9d6fdad2f"

      def install
        bin.install "optimus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/odpf/optimus/releases/download/v0.3.6/optimus_0.3.6_macos_arm64.tar.gz"
      sha256 "05b75ed1d89d814565b4a1409018bbb662ff2ac07f76870da873fee83bfdbd18"

      def install
        bin.install "optimus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/odpf/optimus/releases/download/v0.3.6/optimus_0.3.6_linux_x86_64.tar.gz"
      sha256 "a96d29a06206acfcad223bf368afab6e4b2710ff0a3376748ea50c7ce405ee9f"

      def install
        bin.install "optimus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/odpf/optimus/releases/download/v0.3.6/optimus_0.3.6_linux_arm64.tar.gz"
      sha256 "f5fc31019e66ce36853aabf798487c59fc57e6bf29ca3f1d71f2f7e800298ad9"

      def install
        bin.install "optimus"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/odpf/optimus/releases/download/v0.3.6/optimus_0.3.6_linux_armv6.tar.gz"
      sha256 "8dff46266140b7f520e6f635de14db403c1e016f632efdaf761f1a3628ecd2db"

      def install
        bin.install "optimus"
      end
    end
  end

  depends_on "git"
end
