# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Raccoon < Formula
  desc "Scalable event ingestion tool"
  homepage "https://github.com/raystack/raccoon"
  version "0.2.5"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    on_intel do
      url "https://github.com/raystack/raccoon/releases/download/v0.2.5/raccoon_0.2.5_darwin_amd64.tar.gz"
      sha256 "f51ad94aea62108148924eb6d2f6a0e354307ede8ae12d156dde8393dc028eaa"

      def install
        bin.install "raccoon"
      end
    end
    on_arm do
      url "https://github.com/raystack/raccoon/releases/download/v0.2.5/raccoon_0.2.5_darwin_arm64.tar.gz"
      sha256 "d8c7c7a834b9df56ca2114edea6d6be0c7a60d4f876eb5ac99601006ee0677b4"

      def install
        bin.install "raccoon"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/raystack/raccoon/releases/download/v0.2.5/raccoon_0.2.5_linux_amd64.tar.gz"
        sha256 "e35cbbaa95d87a97e6c20a6fa088cb0423efc1f4bc306c4e24ba9c83c32b3c79"

        def install
          bin.install "raccoon"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/raystack/raccoon/releases/download/v0.2.5/raccoon_0.2.5_linux_arm64.tar.gz"
        sha256 "1e056631289b07aac92bc8b4d5bce804e3587f0392a40311db281f19c904622c"

        def install
          bin.install "raccoon"
        end
      end
    end
  end
end
