# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shield < Formula
  desc "Identity and authorization system"
  homepage "https://github.com/odpf/shield"
  version "0.5.0-alpha"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/odpf/shield/releases/download/v0.5.0-alpha/shield_0.5.0-alpha_macos_x86_64.tar.gz"
      sha256 "743b0c1c30a2c8b1e417ca1b173e702a5a8ca07e7007e4bca32b9ba643834b1f"

      def install
        bin.install "shield"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/odpf/shield/releases/download/v0.5.0-alpha/shield_0.5.0-alpha_macos_arm64.tar.gz"
      sha256 "1b93b3298c897c393c3562bd366688c6b4996ef09317747f030c2a26326bc3df"

      def install
        bin.install "shield"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/odpf/shield/releases/download/v0.5.0-alpha/shield_0.5.0-alpha_linux_armv6.tar.gz"
      sha256 "7358f9f9bd9f9bbd7ac0ed48465e9954b749dc19ec7ac25b251898ad05586df7"

      def install
        bin.install "shield"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/odpf/shield/releases/download/v0.5.0-alpha/shield_0.5.0-alpha_linux_x86_64.tar.gz"
      sha256 "23998d532d0babe80352e1915947ee5619eec4ff2436d8cbad41f1b0e0ffd93e"

      def install
        bin.install "shield"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/odpf/shield/releases/download/v0.5.0-alpha/shield_0.5.0-alpha_linux_arm64.tar.gz"
      sha256 "d916b23a70f3300d9ac9b2013ddb935c4072bbc62a0ed21f9687744a19efdaed"

      def install
        bin.install "shield"
      end
    end
  end
end
