# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shield < Formula
  desc "Identity and authorization system"
  homepage "https://github.com/odpf/shield"
  version "0.5.0-alpha"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/odpf/shield/releases/download/v0.5.0-alpha/shield_0.5.0-alpha_macos_x86_64.tar.gz"
      sha256 "c6710e0675a2b92edf4d1eb2f956eaac4a8cf6028ce2449c4fc7e7e41cd340f3"

      def install
        bin.install "shield"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/odpf/shield/releases/download/v0.5.0-alpha/shield_0.5.0-alpha_macos_arm64.tar.gz"
      sha256 "66cb68b9a3e55fd6a8271555bf322f1617e561209d7b6ed4ccece6bbef0c7f2b"

      def install
        bin.install "shield"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/odpf/shield/releases/download/v0.5.0-alpha/shield_0.5.0-alpha_linux_armv6.tar.gz"
      sha256 "758830b3a2ceef4d83e0b76962c6a3c6a34efed7e613644c8b8e08556d62bff3"

      def install
        bin.install "shield"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/odpf/shield/releases/download/v0.5.0-alpha/shield_0.5.0-alpha_linux_x86_64.tar.gz"
      sha256 "2b46d99484b3793fbd285da6217ca45507372caa887a18106240db8ddb99c6c5"

      def install
        bin.install "shield"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/odpf/shield/releases/download/v0.5.0-alpha/shield_0.5.0-alpha_linux_arm64.tar.gz"
      sha256 "e3b0da3ae69b5ec0d3cf621cbebadec8d9b77b71e7990736f32776b32dfd06e6"

      def install
        bin.install "shield"
      end
    end
  end
end
