# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shield < Formula
  desc "Identity and authorization system"
  homepage "https://github.com/odpf/shield"
  version "0.5.1-alpha"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/odpf/shield/releases/download/v0.5.1-alpha/shield_0.5.1-alpha_macos_arm64.tar.gz"
      sha256 "73e24a5ff9a2357cd7fbe6f69a12b8a1f566996eb8063483f3b2d5b02b7ac50a"

      def install
        bin.install "shield"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/odpf/shield/releases/download/v0.5.1-alpha/shield_0.5.1-alpha_macos_x86_64.tar.gz"
      sha256 "fc6674e4e0b72bc2a845db1d2cf32a8f67c2c62656b32b01c0ea2021f93f474c"

      def install
        bin.install "shield"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/odpf/shield/releases/download/v0.5.1-alpha/shield_0.5.1-alpha_linux_armv6.tar.gz"
      sha256 "a17572f84e4a14eddbee09b302aa3959f29a0af6c5fb8caee47b13629ff11ab3"

      def install
        bin.install "shield"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/odpf/shield/releases/download/v0.5.1-alpha/shield_0.5.1-alpha_linux_x86_64.tar.gz"
      sha256 "b69e08696b1aff695344ffe8f77b6d7f4285958aa6a38505c8f25c4ff74eff0d"

      def install
        bin.install "shield"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/odpf/shield/releases/download/v0.5.1-alpha/shield_0.5.1-alpha_linux_arm64.tar.gz"
      sha256 "c6f81a3bfe48c598d6c61e16c851ee2bce197285239859b340da9e687b9c2afc"

      def install
        bin.install "shield"
      end
    end
  end
end
