# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Siren < Formula
  desc "Universal data observability tool."
  homepage "https://github.com/odpf/siren"
  version "0.5.8"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    url "https://github.com/odpf/siren/releases/download/v0.5.8/siren_0.5.8_macos_x86_64.tar.gz"
    sha256 "49134595bb966e455f8f40827aca953c53badd4c8527552901b5d2448d682d8c"

    def install
      bin.install "siren"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Siren
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/odpf/siren/releases/download/v0.5.8/siren_0.5.8_linux_x86_64.tar.gz"
      sha256 "4669e2694cbe4a8f1f8d4b3cefba20f22f24639ffbf33a0596397adbed4f66b8"

      def install
        bin.install "siren"
      end
    end
  end
end
