# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Siren < Formula
  desc "Universal data observability tool."
  homepage "https://github.com/odpf/siren"
  version "0.5.0"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    url "https://github.com/odpf/siren/releases/download/v0.5.0/siren_0.5.0_macos_x86_64.tar.gz"
    sha256 "31934da30792fdeaee2043dc4360ab65b9a9abd7e3015cf70a88fac6a04b7853"

    def install
      bin.install "siren"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Siren
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/odpf/siren/releases/download/v0.5.0/siren_0.5.0_linux_x86_64.tar.gz"
      sha256 "250e6d833f95515aad0e40da10fbe63f6f71adc122a0598ea7bf6fb74061f9b4"

      def install
        bin.install "siren"
      end
    end
  end
end
