# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stencil < Formula
  desc "Schema registry"
  homepage "https://github.com/raystack/stencil"
  version "0.5.1"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/raystack/stencil/releases/download/v0.5.1/stencil_Darwin_x86_64.tar.gz"
      sha256 "80aa8ff0ff5c4e3856b3f0578e4b88d6d07aa83a28f0fbba82997b257230af5a"

      def install
        bin.install "stencil"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/raystack/stencil/releases/download/v0.5.1/stencil_Darwin_arm64.tar.gz"
      sha256 "e9fce1572f3be5f34adcbc824181ed9963961b398f9467bcd5876ed75d67527f"

      def install
        bin.install "stencil"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/raystack/stencil/releases/download/v0.5.1/stencil_Linux_arm64.tar.gz"
      sha256 "04926367822637d5a3d1939cbe0e737906d8d30637e8508252c09baa63bfea91"

      def install
        bin.install "stencil"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/raystack/stencil/releases/download/v0.5.1/stencil_Linux_x86_64.tar.gz"
      sha256 "2f1e0c2a36abbce68012e0c0a88674ff7c99f6aaed1b2b8175046a7270611f8b"

      def install
        bin.install "stencil"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/raystack/stencil/releases/download/v0.5.1/stencil_Linux_armv6.tar.gz"
      sha256 "a291498803ae15ef7e18595805549120dc9a5ee46b736872090f24455041b8cf"

      def install
        bin.install "stencil"
      end
    end
  end
end
