# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stencil < Formula
  desc "Schema registry"
  homepage "https://github.com/odpf/stencil"
  version "0.2.1"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/odpf/stencil/releases/download/v0.2.1/stencil_0.2.1_macos_arm64.tar.gz"
      sha256 "6aef9594ed4d503e93e421dab0f84f9fdcce4891bc415e15b43a3f2e3b71c46f"

      def install
        bin.install "stencil"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/odpf/stencil/releases/download/v0.2.1/stencil_0.2.1_macos_x86_64.tar.gz"
      sha256 "1232481f7cecd7de5481b434ec16cfa117b4fb69a986d9bc98c5a2686a23b784"

      def install
        bin.install "stencil"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/odpf/stencil/releases/download/v0.2.1/stencil_0.2.1_linux_arm64.tar.gz"
      sha256 "98673068116f30b74f73f6df9eb5b3ee418a317577f5dceb7695ae4899a529de"

      def install
        bin.install "stencil"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/odpf/stencil/releases/download/v0.2.1/stencil_0.2.1_linux_x86_64.tar.gz"
      sha256 "6fa97d98725f3601b1a380a9e936b68e609588bd334ffe38dff1474b393557e8"

      def install
        bin.install "stencil"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/odpf/stencil/releases/download/v0.2.1/stencil_0.2.1_linux_armv6.tar.gz"
      sha256 "1ff331d33c7d93b1e797c35232df3399b2413df0d0906ad4113d0d38481a20a2"

      def install
        bin.install "stencil"
      end
    end
  end

  depends_on "git"
end
